### ISSUE TITLE
why not using Cube MX? i dont know how open the project in keil.

### ISSUE THREAD

**Issue by shredder2003** [satoshinm/pill_serial#8]
why not using Cube MX? i dont know how open the project in keil.

**Comment by satoshinm** [comment]
I initially tried using CubeMX, wrote about it at https://github.com/satoshinm/pill_blink and https://satoshinm.github.io/blog/171212_stm32_blue_pill_arm_development_board_first_look_bare_metal_programming.html, but it was too complicated and bloated for my liking, so I switched to libopencm3, after finding it used in another project. Maybe not the ideal solution either, but, seems to work alright, and allows this project to be used as an example for that library. Sorry I don't know how to open it in Keil either, I use the command-line...
