### ISSUE TITLE
Not building properly under cygwin

### ISSUE THREAD

**Issue by dalbert2** [satoshinm/pill_serial#9]
First, thanks for contributing this!

I'm probably doing something dumb, but the build environment seems to have some issues under windows/cygwin.  First, a brief description of the required environment would help anyone trying to build this: e.g. cygwin including all dependencies (git, python2, make, gnu arm embedded tools (https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads), etc. 

Also, even with the tools that, the libopencm3 top-level makefile fails (and of course it would be nice to comment out all but the f1 target since that's all we need for the bluepill):

...compiles C modules...
  BUILD   lib/stm32/f0
make[1]: Entering directory '/cygdrive/c/Users/david/Documents/EmBitz/pill_serial/libopencm3/lib/stm32/f0'
  AR      libopencm3_stm32f0.a
C:\Program Files (x86)\GNU Tools ARM Embedded\8 2018-q4-major\bin\arm-none-eabi-ar.exe: /cygdrive/c/Users/david/Documents/EmBitz/pill_serial/libopencm3/lib/libopencm3_stm32f0.a: No such file or directory
make[1]: *** [../../Makefile.include:37: /cygdrive/c/Users/david/Documents/EmBitz/pill_serial/libopencm3/lib/libopencm3_stm32f0.a] Error 1
make[1]: Leaving directory '/cygdrive/c/Users/david/Documents/EmBitz/pill_serial/libopencm3/lib/stm32/f0'
make: *** [Makefile:68: lib/stm32/f0] Error 2

The good news is that I can comment out the other targets and go to the libopencm3/lib/stm32/f0 directory and make successfully there and then build the binary successfully at the top level.

Also, I think including the binary seems reasonable since it's for a fixed target.  Several folks have asked, so I've attached the binary I built.  I'll see if I can get the Makefiles fixed too.
[pill_serial.zip](https://github.com/satoshinm/pill_serial/files/2719840/pill_serial.zip)

**Comment by satoshinm** [comment]
Haven't tried building cygwin, no idea about that missing .a file error. Looks like an error in libopencm3 itself? If you can repro the problem without pill_serial, only libopencm3, could be worth reporting to https://github.com/libopencm3/libopencm3. Also I agree it would be good to be able to build only the f0 target in libopencm3, but, I'm not sure if libopencm3 lets you do this.

Thanks for the binaries! Will have to see about including them with https://github.com/satoshinm/pill_serial/issues/6.
